[package]
name = "ct-regex-internal"
version = "0.1.0"
authors = ["Inferno214221 <inferno214221@gmail.com>"]
edition = "2024"
repository = "https://github.com/Inferno214221/compile-time-regex"
license = "GPL-3.0"
description = "A supporting crate for ct-regex, containing the implementation itself."

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
regex-syntax = "0.8.9"
syn = "2.0.117"
arcstr = { version = "1.2.0", optional = true }
bstr = { version = "1.12.1", optional = true }
hipstr = { version = "0.8.0", optional = true }
ecow = { version = "0.2.6", optional = true }

[features]
default = []
arcstr = ["dep:arcstr"]
bstr = ["dep:bstr"]
ecow = ["dep:ecow"]
hipstr = ["dep:hipstr"]
